package rupvm.sminqtask.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import rupvm.sminqtask.database.TASK_TABLE;
import rupvm.sminqtask.database.TASK_FILES_TABLE;

import rupvm.sminqtask.database.TASK_TABLEDao;
import rupvm.sminqtask.database.TASK_FILES_TABLEDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tASK_TABLEDaoConfig;
    private final DaoConfig tASK_FILES_TABLEDaoConfig;

    private final TASK_TABLEDao tASK_TABLEDao;
    private final TASK_FILES_TABLEDao tASK_FILES_TABLEDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tASK_TABLEDaoConfig = daoConfigMap.get(TASK_TABLEDao.class).clone();
        tASK_TABLEDaoConfig.initIdentityScope(type);

        tASK_FILES_TABLEDaoConfig = daoConfigMap.get(TASK_FILES_TABLEDao.class).clone();
        tASK_FILES_TABLEDaoConfig.initIdentityScope(type);

        tASK_TABLEDao = new TASK_TABLEDao(tASK_TABLEDaoConfig, this);
        tASK_FILES_TABLEDao = new TASK_FILES_TABLEDao(tASK_FILES_TABLEDaoConfig, this);

        registerDao(TASK_TABLE.class, tASK_TABLEDao);
        registerDao(TASK_FILES_TABLE.class, tASK_FILES_TABLEDao);
    }
    
    public void clear() {
        tASK_TABLEDaoConfig.getIdentityScope().clear();
        tASK_FILES_TABLEDaoConfig.getIdentityScope().clear();
    }

    public TASK_TABLEDao getTASK_TABLEDao() {
        return tASK_TABLEDao;
    }

    public TASK_FILES_TABLEDao getTASK_FILES_TABLEDao() {
        return tASK_FILES_TABLEDao;
    }

}
