package rupvm.sminqtask.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TASK__TABLE".
 */
@Entity
public class TASK_TABLE {

    @Id
    private Long TASKID;
    private String LOCATIONNAME;
    private Integer UPLOADSTATUS;

    @Generated
    public TASK_TABLE() {
    }

    public TASK_TABLE(Long TASKID) {
        this.TASKID = TASKID;
    }

    @Generated
    public TASK_TABLE(Long TASKID, String LOCATIONNAME, Integer UPLOADSTATUS) {
        this.TASKID = TASKID;
        this.LOCATIONNAME = LOCATIONNAME;
        this.UPLOADSTATUS = UPLOADSTATUS;
    }

    public Long getTASKID() {
        return TASKID;
    }

    public void setTASKID(Long TASKID) {
        this.TASKID = TASKID;
    }

    public String getLOCATIONNAME() {
        return LOCATIONNAME;
    }

    public void setLOCATIONNAME(String LOCATIONNAME) {
        this.LOCATIONNAME = LOCATIONNAME;
    }

    public Integer getUPLOADSTATUS() {
        return UPLOADSTATUS;
    }

    public void setUPLOADSTATUS(Integer UPLOADSTATUS) {
        this.UPLOADSTATUS = UPLOADSTATUS;
    }

}
