package rupvm.sminqtask.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TASK__TABLE".
*/
public class TASK_TABLEDao extends AbstractDao<TASK_TABLE, Long> {

    public static final String TABLENAME = "TASK__TABLE";

    /**
     * Properties of entity TASK_TABLE.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property TASKID = new Property(0, Long.class, "TASKID", true, "TASKID");
        public final static Property LOCATIONNAME = new Property(1, String.class, "LOCATIONNAME", false, "LOCATIONNAME");
        public final static Property UPLOADSTATUS = new Property(2, Integer.class, "UPLOADSTATUS", false, "UPLOADSTATUS");
    };


    public TASK_TABLEDao(DaoConfig config) {
        super(config);
    }
    
    public TASK_TABLEDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TASK__TABLE\" (" + //
                "\"TASKID\" INTEGER PRIMARY KEY ," + // 0: TASKID
                "\"LOCATIONNAME\" TEXT," + // 1: LOCATIONNAME
                "\"UPLOADSTATUS\" INTEGER);"); // 2: UPLOADSTATUS
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TASK__TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TASK_TABLE entity) {
        stmt.clearBindings();
 
        Long TASKID = entity.getTASKID();
        if (TASKID != null) {
            stmt.bindLong(1, TASKID);
        }
 
        String LOCATIONNAME = entity.getLOCATIONNAME();
        if (LOCATIONNAME != null) {
            stmt.bindString(2, LOCATIONNAME);
        }
 
        Integer UPLOADSTATUS = entity.getUPLOADSTATUS();
        if (UPLOADSTATUS != null) {
            stmt.bindLong(3, UPLOADSTATUS);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TASK_TABLE entity) {
        stmt.clearBindings();
 
        Long TASKID = entity.getTASKID();
        if (TASKID != null) {
            stmt.bindLong(1, TASKID);
        }
 
        String LOCATIONNAME = entity.getLOCATIONNAME();
        if (LOCATIONNAME != null) {
            stmt.bindString(2, LOCATIONNAME);
        }
 
        Integer UPLOADSTATUS = entity.getUPLOADSTATUS();
        if (UPLOADSTATUS != null) {
            stmt.bindLong(3, UPLOADSTATUS);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TASK_TABLE readEntity(Cursor cursor, int offset) {
        TASK_TABLE entity = new TASK_TABLE( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // TASKID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // LOCATIONNAME
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2) // UPLOADSTATUS
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TASK_TABLE entity, int offset) {
        entity.setTASKID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLOCATIONNAME(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUPLOADSTATUS(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TASK_TABLE entity, long rowId) {
        entity.setTASKID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TASK_TABLE entity) {
        if(entity != null) {
            return entity.getTASKID();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
