package rupvm.sminqtask.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TASK__FILES__TABLE".
 */
@Entity
public class TASK_FILES_TABLE {

    @Id
    private Long FILEID;
    private Long TASKID;
    private String FILEURL;
    private Integer UPLOADSTATUS;

    @Generated
    public TASK_FILES_TABLE() {
    }

    public TASK_FILES_TABLE(Long FILEID) {
        this.FILEID = FILEID;
    }

    public TASK_FILES_TABLE(String FILEURL) {
        this.FILEURL = FILEURL;
    }

    @Generated
    public TASK_FILES_TABLE(Long FILEID, Long TASKID, String FILEURL, Integer UPLOADSTATUS) {
        this.FILEID = FILEID;
        this.TASKID = TASKID;
        this.FILEURL = FILEURL;
        this.UPLOADSTATUS = UPLOADSTATUS;
    }

    public Long getFILEID() {
        return FILEID;
    }

    public void setFILEID(Long FILEID) {
        this.FILEID = FILEID;
    }

    public Long getTASKID() {
        return TASKID;
    }

    public void setTASKID(Long TASKID) {
        this.TASKID = TASKID;
    }

    public String getFILEURL() {
        return FILEURL;
    }

    public void setFILEURL(String FILEURL) {
        this.FILEURL = FILEURL;
    }

    public Integer getUPLOADSTATUS() {
        return UPLOADSTATUS;
    }

    public void setUPLOADSTATUS(Integer UPLOADSTATUS) {
        this.UPLOADSTATUS = UPLOADSTATUS;
    }

}
